[package]
name = "rogueTutorial"
version = "0.1.0"
authors = ["Dylan <dylanswaters@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
